### ISSUE TITLE
Work Request

### ISSUE THREAD

**Issue by jkalili** [lmu-cmsi284-spring2020/assignments#2]
Hi @dondi @afiller1! Can I please get my assignment whenever it's convenient. Thanks :)

Jason

**Comment by dondi** [comment]
Hi @jkalili —please post the issue under your specifically-designated repository (the one you get when you click the _Setup_ button next to the assignment on the course website) in order to get the exercises. Thanks!

**Comment by dondi** [comment]
All good now.
