### ISSUE TITLE
Wow I am really late. Sorry. Can I have my excercises?

### ISSUE THREAD

**Issue by Jortiz23** [lmu-cmsi284-spring2020/assignments#4]
@dondi, @afiller1

**Comment by dondi** [comment]
Hi @Jortiz23  —please post the issue under your specifically-designated repository (the one you get when you click the Setup button next to the assignment on the course website) in order to get the exercises. Without that repository, we have no place to put your individualized exercise set. Thanks!

**Comment by Jortiz23** [comment]
sorry!
